<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/x26-1-660x368.png.pagespeed.ic.n4V0mCXx4C.webp', 'Laporan Ketua Panitia oleh Kepala BPPTIK, DR. Nusirwan S.Ag, M.Si', 'Laporan Ketua Panitia oleh Kepala BPPTIK, DR. Nusirwan S.Ag, M.Si'); ?> <p><strong>BPPTIK</strong>- Balai Pelatihan dan Pengembangan Teknologi Informasi dan Komunikasi (BPPTIK) menyelenggarakan Pelatihan Teknis Bidang TIK untuk Penyuluh Agama Angkatan 1,Training of Trainers Digital Entrepreneurship Academy(DEA), Pelatihan dan Sertifikasi Junior Cyber Security, dan Cyber Security Analyst dalam rangka Witness Penambahan ruang lingkup LSP BPPTIK secara online.
</p>
<p>Kegiatan dilaksanakan pada tanggal 26 Juli - 12 Agustus 2021 secara Online, melalui media B-Learning BPPTIK dan aplikasi video conference. Kegiatan diawali pembacaana laporan kegiatan oleh Kepala BPPTIK , DR.Nusirwan, S.Ag, M.Si. Pada kesempatan tersebut beliau menyampaikan tujuan kegiatan ini yaitu meningkatkan kompetensi teknis bidang TIK bagi penyuluh agama di lingkungan Kementerian Agama dalam mengelola TIK secara profesional dalam melakukan pekerjaannya, meningkatkan pelayanan publik berbasis e-government, memastikan dan memelihara kompetensi calon pengajar DEA,memastikan dan memelihara kompetensi peserta Cyber Security Analyst dna Menambahkan ruang lingkup skema JSA dan CSA pada LSP BPPTIK.</p>
<p>Jumlah peserta yang mengikuti pelatihan adalah sebanyak 533 orang yang berasal dari Kementerian Agama seluruh Indonesia, President University, STIMIK Bani Saleh, Universitas Indraprasta PGRI, Universitas Bina Insani, SMK Bina Mitra dan SMK Islam Darurohman dan untuk tenaga pengajar berjumlah 26 orang yang berasal dari Kementerian Agama, Universitas Padjajaran, Universitas Muhammadiyah Jakarta, Universitas Nahdatul Ulama Kalsel dan BPPTIK Kominfo.</p>
<p>Pembukaan turut dihadiri oleh Direktur Penerangan Agama Islam Kementerian Agama; Drs. H. Syamsul Bahri, M.Pd.I.; Ketua STMIK Bani Saleh, Bapak Drs. Taufik Maulana, MBA.;WakilRektor IV Bidang Kerjasama Universitas Indraprasta PGRI, Ambar Tri Hapsari, M.Kom., Wakil Rektor III President University, Bapak Dr. Josep Ginting, S.E., M.M., Dekan Fakultas Komputer President University, Ir. Rila Mandala, M.Eng., Ph.D., Dekan Fakultas Bisnis President University, Ibu Dr. Maria Jacinta Arquisola, BA., MHRM., Dekan Fakultas Informatika Universitas Bina Insani, Didik Setiyadi, S.Kom., M.Kom, Kepala SMK Islam Darurrohman, Bapak M. Yadi, S.Pd., MM., Wakil Kepala Kesiswaan SMK Binamitra, Bapak Tato Purwanto, M.Pd., Ketua Pokja GTA DTS Kominfo, Bapak Ir. Herry Abdul Aziz, M.Eng., Ketua Pokja DEA DTS Kominfo, Bapak Riza Azmi, S.Kom., M.Kom. dan Kepala BPPTIK, DR. Nusirwan S.Ag, M.Si..</p>
<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/x26-2-660x368.png.pagespeed.ic.bm6Zvw4rNf.webp', 'Sambutan dan Pembukaan secara resmi oleh Kepala Badan Litbang SDM Kementerian Kominfo, DR. Hary Budiarto, M.Kom', 'Sambutan dan Pembukaan secara resmi oleh Kepala Badan Litbang SDM Kementerian Kominfo, DR. Hary Budiarto, M.Kom');
?>
<p>Kegiatan dibuka secara resmi oleh Kepala Badan Litbang SDM, DR. Hary Budiarto, M.Kom, pada hari Senin (26/07/2021).Dalam pemaparannya, beliau menyampaikan program Digitalent Scholarship (DTS), merupakan program yang diberikan kepada para talenta digital Indonesia sejak tahun 2018. Pada tahun 2021, DTS didesain untuk menciptakan ekosistem yang seimbang dalam peta hentahelik, yaitu pemerintah,komunitas atau masyarakat. instituisi pedidikan tinggi dunia usaha dan media untuk dapat menjadi fasilitator dan akseleratir pendukung ekonomi digital.</p>
<p>Selain itu juga beliau juga menyampaikan DTS bertujuan untuk meningkatkan daya saing, kreatifitas profesioanalisme SDM di bidang TIK untuk angkatan kerja muda, masyarakat umum dan ASN Indonesia.</p>
<p>DTS 2021 menjadi 8 garis besar, VGA, VSGA, Thematic ACADEMY, Pro academy, GTA, DEA dan TSA. Pelatihan penyuluh agama termasuk dalam program Government Talent Academy(GTA). Tujuan pelatihan ini agar dapat memberikan pemahaman secara masive dengan memanfaatkan TIK.</p>
<p>Penyuluh agama yang memiliki kompetensi di bidang TIK sangat diperlukan karena banyak sekali saat ini masyarakat terjebak dalam Hoax, banyak materi kurang benar seperti paham radikalisme. Oleh karena itu penting penyuluh agama dalam ruang lingkup digital,bisa memberikan pemahaman yg masive dan komprehensif pada masyarakat dengan memanfatkan TIK dengan menyampaikan informasi yang benar sesuai kaidah agama Islam.</p>
<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/x26-3-660x351.jpg.pagespeed.ic.717U68MsB0.webp', 'Sesi Foto Bersama', 'Sesi Foto Bersama');
?>
<p>Pada akhir pemaparan, beliau juga menyampaikan ke peserta selamat mengikuti pelatihan dan dapat mengikuti pelatihan sebaik-baiknya. Pembukaan pelatihan ini ditutup dengan doa bersama. (bpptik/ds/rie)</p>