<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/xtot1-1-660x371.png.pagespeed.ic.3nwzfrxxhZ.webp', 'Sambutan dan Pembukaan Secara Resmi oleh Kepala Badan Litbang SDM Kementerian Kominfo', 'Sambutan dan Pembukaan Secara Resmi oleh Kepala Badan Litbang SDM Kementerian Kominfo');
?>
<p><strong>BPPTIK</strong> - Balai Pelatihan dan Pengembangan Teknologi Informasi dan Komunikasi (BPPTIK) menyelenggarakan ToT Pelatihan Penyuluh Agama bagi Aparatur Sipil Negara (ASN) Kementerian Agama Angkatan II Tahun 2021 di BPPTIK Kominfo secara Daring.</p>
<p>Kegiatan dilaksanakan pada tanggal 21 Juli - 03 Agustus 2021 secara Daring melalui media B-Learning BPPTIK dan aplikasi video conference Zoom Meeting. Tujuan kegiatan ini adalah meningkatkan kompetensi teknis bidang TIK bagi Penyuluh Agama di lingkungan Kementerian Agama dalam menggunakan dan/atau mengelola TIK secara professional dalam melaksanakan pekerjaanya. Selain itu, peserta diharapkan dapat meningkatkan pelayanan public berbasis e-Government. Pelatihan ini diselenggarakan dengan sumber dana dari DIPA BPPTIK Tahun Anggaran 2021</p>
<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/xtot1-2-660x371.png.pagespeed.ic.FueswgsqIL.webp', 'Lap
                oran Ketua Panitia Penyelenggara oleh Kepala BPPTIK', 'Laporan Ketua Panitia Penyelenggara oleh Kepala BPPTIK');
?>
<p>Pembukaan diawali dengan laporan ketua panitia penyelenggara, Pak Nusirwan, selaku Kepala oleh Kepala Balai Pelatihan dan Pengembangan Teknologi Informasi dan Komunikasi (BPPTIK) Kementerian Kominfo. Pelatihan pada kegiatan ini mengacu kepada Unit Kompetensi SKKNI Bidang Pengoperasian Komputer dan dilengkapi dengan kompetensi Penggunaan Perangkat Lunak Pengolah Gambar Tingkat Dasar. Jumlah peserta yang mengikuti pelatihan ini adalah sebanyak 60 orang yang merupakan penyuluh agama di lingkungan Kementerian Agama dari berbagai wilayah di Indonesia. Jumlah tenaga pengajar berjumlah 4 orang yang berasal dari BPPTIK, LAN, dan Ditjen Aptika Kominfo. Pembukaan turut dihadiri oleh Sub Koordinator Penyelenggara Pelatihan Aparatur BPPTIK, Pak Hary Yudhanto, Direktur Penerangan Agama Islam Kementerian Agama, Kepala Subdit Penyuluh Agama Islam Kementerian Agama, Kepala Seksi Agama Islam Kementerian Agama, para tenaga pengajar, serta para peserta pelatihan.</p>
<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/xtot1-3-660x371.png.pagespeed.ic.CKGKhttUm8.webp', 'Sesi Foto Bersama', 'Sesi Foto Bersama');
?>
<p>Kemudian dilanjutkan oleh Pak Hary Budiarto, Kepala Badan Litbang SDM Kementerian Kominfo untuk memberikan sambutan serta membuka kegiatan ini secara resmi. Dalam sambutannya, Kepala Badan Litbang SDM Kementerian Kominfo menyampaikan Instruksi Presiden melalui Menteri Kominfo terkait Program Akselerasi Transformasi Digital. Indonesia memiliki target 9 juta talenta digital pada tahun 2030. Jika dirincikan, setiap tahun Indonesia harus menghasilkan 600 ribu talenta digital. Beliau mengucapkan terima kasih kepada Kementerian Agama yang telah turut berperan dalam upaya pencapaian target tersebut melalui kegiatan ini.</p>
<p>Kepala Badan Litbang SDM juga menginformasikan terkait Digital Talent Scholarship yang terdiri dari beberapa program, yaitu FGA, VSGA, TA, PROA, DEA, GTA, dan TSA. Pelatihan ini merupakan salah satu bidang dalam program GTA (Government Transformation Academy). Melaui bidang ini, para penyuluh agama dapat melaksanakan tugas dan fungsinya menggunakan teknologi digital. Beliau berharap, setelah mengikuti kegiatan ini para penyuluh agama dapat memberikan pemahaman yang masif dan komprehensif dengan berbagai media sehingga masyarakat terhindar dari informasi hoax. Pembukaan pelatihan ini ditutup dengan doa bersama. (bpptik/nfm/rie)</p>