<?php pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/xKepala-Badan-Litbang-SDM-Kominfo-Membuka-Pelatihan-dan-Sertifikasi-Kompetensi-Bidang-TIK-Berbasis-SKKNI-Gelombang-Ke-7-Tahun-2021-Secara-Online-660x381.png.pagespeed.ic.A-skczj_6n.webp', 'Kepala Badan Litbang SDM Kominfo Membuka Pelatihan dan Sertifikasi Kompetensi Bidang TIK Berbasis SKKNI Gelombang Ke-7 Tahun 2021 Secara Online', 'Kepala Badan Litbang SDM Kominfo Membuka Pelatihan dan Sertifikasi Kompetensi Bidang TIK Berbasis SKKNI Gelombang Ke-7 Tahun 2021 Secara Online');
?>
<p><strong>BPPTIK</strong> - Balai Pelatihan dan Pengembangan Teknologi Informasi dan Komunikasi kembali menyelenggarakan Pelatihan dan Sertifikasi Kompetensi Online Bidang TIK Berbasis Standar Kompetensi Kerja Nasional Indonesia (SKKNI) Gelombang Ke-7 Tahun 2021. Upacara pembukaan dilaksanakan secara online pada hari Senin tanggal 5 Juli 2021 melalui aplikasi online conference. Kegiatan dibuka secara resmi oleh Kepala Badan Litbang SDM Kementerian Kominfo, Hary Budiarto; dengan dihadiri oleh Kepala BPPTIK, Nusirwan; Sub Koordinator BPPTIK; dan tenaga pengajar.</p>
<p>Kegiatan Pelatihan dan Sertifikasi Kompetensi Online Bidang TIK Berbasis SKKNI Gelombang Ke-7 Tahun 2021 diselenggarakan pada tanggal 5 Juli - 3 Agustus 2021. Kegiatan ini terdiri dari pembelajaran mandiri dengan pendampingan pengajar melalui Learning Management System (LMS) BPPTIK, live session dengan pengajar, serta sertifikasi online melalui aplikasi online conference. Jumlah peserta pada Pelatihan dan Sertifikasi Kompetensi Online Bidang TIK Berbasis SKKNI Gelombang Ke-7 Tahun 2021 ini sebanyak sebanyak 1.044 orang. Para peserta terbagi ke dalam 5 (lima) program pelatihan dan skema sertifikasi yang mengacu pada Skema Sertifikasi Okupasi Nasional, yaitu Junior Office Operator sebanyak 341 orang peserta, Junior Web Developer sebanyak 282 orang peserta, Junior Graphic Designer sebanyak 223 orang peserta, Junior Network Administrator sebanyak 114 orang peserta, dan Teknisi Utama Jaringan Komputer sebanyak 84 orang peserta. Tenaga pengajar berjumlah 28 orang yang berasal dari BPPTIK Kominfo, President University, BBPLK Bekasi, dan Relawan TIK Indonesia.</p>
<p>Kepala Badan Litbang SDM menyampaikan apresiasi terhadap seluruh pihak yang terlibat dalam pelaksanaan kegiatan ini. Berikutnya, beliau menyampaikan pula paparan dan sambutan bagi peserta dengan tema -Strategi Pengembangan SDM Bidang TIK Secara Nasional-. Beliau menjelaskan tentang arahan Presiden Republik Indonesia dalam Perencanaan Transformasi Digital untuk menghadapi Revolusi Industri 4.0.</p>
<p>Arahan Presiden tersebut diterjemahkan ke dalam roadmap Kominfo dengan target Indonesia Emas 2045: Keluar dari Middle Income Trap. Target tersebut sekaligus mendorong Indonesia menjadi negara maju, bukan lagi negara berkembang. Diharapkan pula, pada tahun tersebut tercipta 2,5 juta lapangan pekerjaan yang terkait Industri 4.0. Kominfo membagi roadmap tersebut menjadi 3 bagian yaitu penyiapan SDM, kebijakan serta tata kelola.</p>
<?php
pageImage('#', 'https://bpptik.kominfo.go.id/wp-content/uploads/2021/07/xKepala-Badan-Litbang-SDM-Kominfo-Memberikan-Arahan-Mengenai-Strategi-Pengembangan-SDM-Bidang-TIK-Secara-Nasional-660x288.png.pagespeed.ic.hqZrrLsMSh.webp', 'Kepala Badan Litbang SDM Kominfo Memberikan Arahan Mengenai Strategi Pengembangan SDM Bidang TIK Secara Nasional', 'Kepala Badan Litbang SDM Kominfo Memberikan Arahan Mengenai Strategi Pengembangan SDM Bidang TIK Secara Nasional');
?>
<p>Pelatihan dan Sertifikasi Kompetensi Online Bidang TIK Berbasis SKKNI ini merupakan salah satu strategi pelaksanaan roadmap tersebut pada bagian penyiapan SDM. Program pelatihan ini berkorelasi dengan program <a href='http://digitalent.kominfo.go.id/'> Digital Talent Scholarship (DTS)</a> atau Beasiswa untuk Talenta Digital sebagai program unggulan Kementerian Kominfo. Program ini dilengkapi pula dengan sertifikasi yang menjadi kesempatan bagi para peserta untuk meningkatkan pengetahuan dan keterampilan, sikap serta daya saing di bidang TIK.</p>
<p>Lebih lanjut, Kepala Badan Litbang SDM menyampaikan pula, harapan beliau agar para peserta yang nantinya menjadi alumni pelatihan dapat membuat profil siap kerja yang dilengkapi dengan informasi kompetensi tersertifikasi melalui aplikasi <a href='https://simonas.kominfo.go.id/'>SIMONAS</a> sehingga meningkatkan penyerapan tenaga kerja bidang TIK.</p>
<p>BPPTIK di bawah koordinasi Kementerian Kominfo turut berkomitmen untuk menyelenggarakan Pelatihan dan Sertifikasi Kompetensi Online Bidang TIK Berbasis SKKNI Tahun 2021 dengan tidak membebankan biaya apapun kepada peserta. Seluruh pembiayaan program ini dibebankan kepada APBN BPPTIK Tahun 2021. Selain itu, BPPTIK memiliki program pelatihan dan pemanfaatan fasilitas maupun kerja sama lainnya di bidang pelatihan TIK melalui skema pembiayaan PNBP berdasarkan PP 80/2015. (bpptik/fm/lpa)</p>